// <auto-generated />
using System;
using DiplomaSite3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiplomaSite3.Migrations
{
    [DbContext(typeof(DiplomaSite3Context))]
    partial class DiplomaSite3ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiplomaSite2.Models.UserModel", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserID");

                    b.ToTable("UserModel");

                    b.HasDiscriminator<string>("Discriminator").HasValue("UserModel");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DiplomaSite3.Models.DiplomaModel", b =>
                {
                    b.Property<Guid>("DiplomaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DefendDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Grade")
                        .HasPrecision(5, 3)
                        .HasColumnType("decimal(5,3)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("StudentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TeacherID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiplomaID");

                    b.HasIndex("StudentID")
                        .IsUnique()
                        .HasFilter("[StudentID] IS NOT NULL");

                    b.HasIndex("TeacherID");

                    b.ToTable("DiplomaModel");
                });

            modelBuilder.Entity("DiplomaSite3.Models.StudentModel", b =>
                {
                    b.HasBaseType("DiplomaSite2.Models.UserModel");

                    b.Property<string>("FacultyNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("StudentModel");
                });

            modelBuilder.Entity("DiplomaSite3.Models.TeacherModel", b =>
                {
                    b.HasBaseType("DiplomaSite2.Models.UserModel");

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("TeacherModel");
                });

            modelBuilder.Entity("DiplomaSite3.Models.DiplomaModel", b =>
                {
                    b.HasOne("DiplomaSite3.Models.StudentModel", "Student")
                        .WithOne("AssignedDiploma")
                        .HasForeignKey("DiplomaSite3.Models.DiplomaModel", "StudentID");

                    b.HasOne("DiplomaSite3.Models.TeacherModel", "Teacher")
                        .WithMany("PostedDiplomas")
                        .HasForeignKey("TeacherID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("DiplomaSite3.Models.StudentModel", b =>
                {
                    b.Navigation("AssignedDiploma");
                });

            modelBuilder.Entity("DiplomaSite3.Models.TeacherModel", b =>
                {
                    b.Navigation("PostedDiplomas");
                });
#pragma warning restore 612, 618
        }
    }
}
